config/routes.rb
Rails.application.routes.draw do
  resource :wizard do
    get :step1
    get :step2
    get :step3
    get :step4

    post :validate_step
  end
  root to: 'secrets#recent'
  
  resources :secrets, except: [:show]
  resources :sessions, only: [:create, :new, :destroy]
  resources :comments
  
  post '/secret/upvote', to: "secrets#upvote"
  post '/secret/downvote', to: "secrets#downvote"
  post '/secret/report', to: "secrets#report"
  get '/secret/random', to: "secrets#get_random_secret"
  get '/admin', to: "secrets#admin"
  get '/secrets/recent', to: "secrets#most_popular"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :secrets
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :secret
end

app/models/secret.rb
class Secret < ApplicationRecord
  belongs_to :category
  has_many :comments
end

app/models/user.rb
class User
  include ActiveModel::Model

  attr_accessor :username, :password

  def login_valid?
    username == ENV['ADMIN_USERNAME'] && password == ENV['ADMIN_PASS']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :prepare_meta_tags, if: "request.get?"

  ApplicationNotAuthenticated = Class.new(StandardError)

  rescue_from ApplicationNotAuthenticated do
    respond_to do |format|
      format.json { render json: { errors: [message: "401 Not Authorized"] }, status: 401 }
      format.html do
        flash[:notice] = "Not Authorized to access this page, plese log in"
        redirect_to new_session_path
      end
      format.any { head 401 }
    end
  end

  def authentication_required!
    session[:current_user] || raise(ApplicationNotAuthenticated)
  end

  def prepare_meta_tags(options={})
    site_name   = "Secret So Far"
    title       = "Anonymously Share Your Secrets"
    description = "Anonymously share your secrets and get rid of the heavy weight you've been carrying around!"
    image       = options[:image] || "//farm5.staticflickr.com/4313/35292896663_8c65d83fc2_o.png"
    icon		= "//farm5.staticflickr.com/4313/35292896663_8c65d83fc2_o.png"
    current_url = request.url

    # Let's prepare a nice set of defaults
    defaults = {
      site:        site_name,
      title:       title,
      image:       image,
      description: description,
      keywords:    %w[web software development mobile app],
      twitter: {
        site_name: site_name,
        site: '@thecookieshq',
        card: 'summary',
        description: description,
        image: image
      },
      og: {
        url: current_url,
        site_name: site_name,
        title: title,
        image: image,
        description: description,
        type: 'website'
      }
    }

    options.reverse_merge!(defaults)

    set_meta_tags options
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    secret = Secret.find(params[:secret])
    comment_body = params[:body]
    comment = Comment.create(body: comment_body)
    secret.comments.push(comment)

    if comment.save
      respond_to do |format|
        format.json { 
          render json: {:status => "ok", :comment => comment }
        }
      end
    else
      respond_to do |format|
        format.json { 
          render json: {:status => "nok" }
        }
      end
    end
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :check_if_authenticated, only: [:admin, :destroy]
  def most_popular
  	@secrets = Secret.all
  	@secrets = (@secrets.sort_by { |a| a.upvotes }).reverse!
    @secret = Secret.find_by_id(params[:secret]) if params[:secret]
  end

  def admin
    @secrets = Secret.where(:reported => true)
  end

  def report
    secret = Secret.find_by_id(params[:secret])
    secret.reported = true
  
    if secret.save
      respond_to do |format|
        format.json { 
          render json: {:status => "ok" }
        }
      end
    else
      respond_to do |format|
        format.json { 
          render json: {:status => "nok" }
        }
      end
    end
  end

  def index
    if params[:category]
      @secrets = Category.find_by_name(params[:category]).secrets
    else
      @secrets = Secret.all
    end

    @secrets = (@secrets.sort_by { |a| a.upvotes }).reverse!
  end

  def recent
    @secrets = Secret.all.order('created_at DESC')
  end

  def get_random_secret
    secret = Secret.all[(rand(0..Secret.all.length - 1))]
    if secret
      status == "ok"
    else
      status == "nok"
    end
    respond_to do |format|
      format.json { 
        render json: {:status => status, :secret => secret }
      }
    end
  end

  def upvote
  	secret = Secret.find_by_id(params[:secret])
  	if !cookies[:upvoted].to_s.include?("secret-#{secret.id}")
  	  secret.update_attributes(:upvotes => secret.upvotes+1)
  	  cookies[:upvoted] = "#{cookies[:upvoted]}secret-#{secret.id};"
  	  status = "ok"
    else
      status = "nok"
    end
    respond_to do |format|
      format.json { 
        render json: {:status => status, :upvotes_value => secret.upvotes }
      }
    end
  end

  def downvote
  	secret = Secret.find_by_id(params[:secret])
  	if !cookies[:downvoted].to_s.include?("secret-#{secret.id}")
  	  secret.update_attributes(:upvotes => secret.upvotes-1)
  	  cookies[:downvoted] = "#{cookies[:downvoted]}secret-#{secret.id};"
  	  status = "ok"
    else
      status = "nok"
    end
    respond_to do |format|
      format.json { 
        render json: {:status => status, :upvotes_value => secret.upvotes }
      }
    end
  end

  def destroy
    Secret.find_by_id(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_back }
    end
  end

  private

  def check_if_authenticated
    unless session[:current_user]
      redirect_to '/'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # sleep 2 # you can add sleep here  if you want to  slow down brute force attack
              # for normal application this is bad idea but for one
              # user login no-one care

    user_params = params.require(:user)

    @user = User.new
      .tap { |su| su.username = user_params[:username] }
      .tap { |su| su.password = user_params[:password] }

    if @user.login_valid?
      session[:current_user] = true
      redirect_to '/admin'
    else
      @user.password = nil
      flash[:notice] = 'Sorry, wrong credentils'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_action :load_secret_wizard, except: %i(validate_step)

  def validate_step
    current_step = params[:current_step]

    @secret_wizard = wizard_secret_for_step(current_step)
    @secret_wizard.secret.attributes = secret_wizard_params
    session[:secret_attributes] = @secret_wizard.secret.attributes

    if @secret_wizard.valid?
      next_step = wizard_secret_next_step(current_step)
      create and return unless next_step

      redirect_to action: next_step
    else
      render current_step
    end
  end

  def create
    if @secret_wizard.secret.save
      session[:secret_attributes] = nil
      redirect_to root_path, notice: 'Secret succesfully created!'
    else
      redirect_to({ action: Wizard::Secret::STEPS.first }, alert: 'There were a problem when creating the secret.')
    end
  end

  private

  def load_secret_wizard
    @secret_wizard = wizard_secret_for_step(action_name)
  end

  def wizard_secret_next_step(step)
    Wizard::Secret::STEPS[Wizard::Secret::STEPS.index(step) + 1]
  end

  def wizard_secret_for_step(step)
    raise InvalidStep unless step.in?(Wizard::Secret::STEPS)

    "Wizard::Secret::#{step.camelize}".constantize.new(session[:secret_attributes])
  end

  def secret_wizard_params
    params.require(:secret_wizard).permit(:user_gender, :user_age, :secret_body, :category_id)
  end

  class InvalidStep < StandardError; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wizard_helper.rb
module WizardHelper
end

app/views/layouts/_categories_modal.html.erb
<div id="pick-category-modal" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header shadow">
        <h5 class="modal-title">Pick a category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
                  <div class="row">
            <div class="col-md-4">
              <div class="row">
                  <div class="col-12 text-center">
                    <%= radio_button_tag 'category', "funny", false, class: "gender-radio category-funny" %>
                  </div>
                  <div class="col-12 text-center">
                    Funny
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="row">
                  <div class="col-12 text-center">
                    <%= radio_button_tag 'category', "sexy", false, class: "gender-radio category-hot" %>
                  </div>
                  <div class="col-12 text-center">
                    Sexy
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="row">
                  <div class="col-12 text-center">
                    <%= radio_button_tag 'category', "love & relationships", false, class: "gender-radio category-love" %>
                  </div>
                  <div class="col-12 text-center">
                    Love & Relationships
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="row">
                  <div class="col-12 text-center">
                    <%= radio_button_tag 'category', "rant", false, class: "gender-radio category-rant" %>
                  </div>
                  <div class="col-12 text-center">
                    Rants
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="row">
                  <div class="col-12 text-center">
                    <%= radio_button_tag 'category', "embarassing", false, class: "gender-radio category-embarassing" %>
                  </div>
                  <div class="col-12 text-center">
                    Embarassing
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="row">
                  <div class="col-12 text-center">
                    <%= radio_button_tag 'category', "miscellaneous", false, class: "gender-radio category-misc" %>
                  </div>
                  <div class="col-12 text-center">
                    Miscellaneous
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
      <div class="modal-footer text-center">
        <%= link_to "Done", secrets_path(), :class => "btn btn-primary select-category-btn shadow" %>
      </div>
    </div>
  </div>
</div>

<script>
  var category_url = $(".select-category-btn").attr("href");
  $('input[type=radio][name=category]').change(function() {
    console.log($(this).val());
    $(".select-category-btn").attr("href", category_url + "?category=" + encodeURIComponent($(this).val()));
    });
</script>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-103030622-1', 'auto');
	  ga('send', 'pageview');
	</script>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse belooga-navbar">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">
        <img src="//farm5.staticflickr.com/4313/35292896663_8c65d83fc2_o.png" style="width: 150px;">
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <% if session[:current_user] %>
              <li class="nav-item">
                <%= link_to 'Log OUT', session_path('logout'), method: :delete, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item <%= active_class(root_path) %>">
                <a class="nav-link" href="<%= root_path %>"> Most Recent <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item <%= active_class(secrets_recent_path) %>">
                <a class="nav-link" href="<%= secrets_recent_path %>"> Most Popular <span class="sr-only">(current)</span></a>
            </li>
<!--             <li class="nav-item random-secret">
                <span class="nav-link" style="cursor: pointer;" data-toggle="modal" data-target="#random-secret-modal">Random Secret</span>
            </li> -->
            <li class="nav-item  <%= active_class(secrets_path) %>">
                <a class="nav-link" href="#"  data-toggle="modal" data-target="#pick-category-modal">Categories</a>
            </li>
            <li class="nav-item <%= active_class(step1_wizard_path) %>">
                <%= link_to "Share a secret", step1_wizard_path, class: 'btn btn-primary shadow' %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/_random_secret_modal.html.erb
<div id="random-secret-modal" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header shadow">
        <h5 class="modal-title">Pick a category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="card secret-card shadow">
            <div class="card-header text-center shadow">
                <h4 id="user-gender-age"> </h4>
              </div>
              <div class="card-block">
                <p id="secret-body" class="card-text"> </p>
                <p> </p>
                <p class="time-distance pull-right"> </p>
              </div>
              <div class="card-footer text-muted">
                Upvotes: <span id="upvotes">  </span>
                <div class="up-down-votes pull-right">
                  <i class="fa fa-thumbs-up change-upvotes upvote" aria-hidden="true" data-action="upvote" data-secret=""></i> | <i class="fa fa-thumbs-down change-upvotes downvote" aria-hidden="true" data-action="downvote" data-secret=""></i>
                </div>
            </div>
          </div>  
        </div>
      </div>
      <div class="modal-footer text-center">
        <%= link_to "Done", secrets_path(), :class => "btn btn-primary select-category-btn shadow" %>
      </div>
    </div>
  </div>
</div>

<script>
  $("#random-secret-modal").on("shown.bs.modal", function(){
    $.ajax({
        url: "/secret/random",
        success: function(data){
          console.log(data);
          $('.random-secret-modal .modal-header').addClass(data.secret.user_gender);
          $('.random-secret-modal #user-gender-age').html(data.secret.user_gender + " - " + data.secret.user_age + " y/o");
        }
      })
  });
</script>

app/views/layouts/_secret_modal.html.erb
<% if @secret %>
  <div id="secret-modal" class="modal fade">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style="background-color: transparent; border: none;">
<!--         <div class="modal-header shadow">
          <h5 class="modal-title">Pick a category</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div> -->
        <div class="modal-body">
          <div class="container">
            <div class="card secret-card shadow">
              <div class="card-header <%= @secret.user_gender.downcase %> text-center shadow">
                  <h4> <%= @secret.user_gender.capitalize %> - <%= @secret.user_age %> y/o </h4>
                </div>
                <div class="card-block">
                  <p class="card-text"><%= @secret.secret_body %> </p>
                  <p> </p>
                  <div class="time-distance pull-left"> 
                    <%= distance_of_time_in_words(@secret.created_at, Time.now) %> ago in <a href="<%= secrets_path %>?category=<%= URI::escape(@secret.category.name) %>">#<%= @secret.category.name %></a>  
                  </div>
                  <br>
                  <div class="pull-left">
                    <%= social_share_button_tag("Hey you! Look at this secret!", :url => "#{ENV['DOMAIN_URL']}?secret=#{@secret.id}") %>
                  </div>
                </div>
                <div class="card-footer text-muted">
                  <a class="comments-load pull-left pointer" onclick="loadDisqus($(this), '<%= @secret.id %>', 'localhost:4004'+'<%= secret_path(@secret)%>');"> <i class="fa fa-comment" aria-hidden="true"></i>
  Show comments </a>
                  <div class="upvotes-container pull-right">
                    Upvotes: <span id="upvotes-<%= @secret.id %>"> <%= @secret.upvotes %> </span>
                  <div class="up-down-votes pull-right" style="padding-left: 30px;">
                    <i class="fa fa-thumbs-up change-upvotes upvote" aria-hidden="true" data-action="upvote" data-secret="<%= @secret.id %>"></i> | <i class="fa fa-thumbs-down change-upvotes downvote" aria-hidden="true" data-action="downvote" data-secret="<%= @secret.id %>"></i>
                  </div>
                  </div>
              </div>
            </div> 
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
      $(document).ready(function(){
        var hasParam = window.location.href.indexOf("secret=");
        if(hasParam) {
           $('#secret-modal').modal();
        }
      })
  </script>
<% end %>

app/views/secrets/_secrets_list.html.erb
<style>
	@media(device-width: 768px) and (device-height: 1024px){
    ::-webkit-scrollbar {
        -webkit-appearance: none;
        width: 7px;
    }
    ::-webkit-scrollbar-thumb {
        border-radius: 4px;
        background-color: rgba(0,0,0,.5);
        -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
    }
}

</style>
<div class="container secret-listing">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<% @secrets.each do |secret| %>
				<div class="row">
					<div class="col-md-12">
						<div class="card secret-card shadow" data-secret="<%= secret.id %>">
							<div class="card-header <%= secret.user_gender.downcase %> text-center shadow">
						    	<h4> <%= secret.user_gender.capitalize %> - <%= secret.user_age %> y/o </h4>
						  	</div>
						  	<div class="card-block" data-secret="<%= secret.id %>">
						  			<% if session[:current_user] %>
						  				<div class="delete-box">
						  					<%= link_to 'Delete', secret_path(secret), method: :delete %>
						  				</div>
						  			<% else %>
						  				<div class="report-box">
								  			<span class="report-label"> Report </span>
								  			<i class="report-icon fa fa-exclamation-triangle" data-secret="<%= secret.id %>" aria-hidden="true"></i>
							  			</div>
							  		<% end %>
						    	<p class="card-text"><%= secret.secret_body %></p>
						    	<p> </p>
						    	<div class="time-distance pull-left"> 
						    		<%= distance_of_time_in_words(secret.created_at, Time.now) %> ago in <a href="<%= secrets_path %>?category=<%= URI::escape(secret.category.name) %>">#<%= secret.category.name %> <img style="height: 20px;" src="<%= secret.category.icon %>"></a>  
						    	</div>
						    	<br>
						    	<div class="pull-left">
						    		<%= social_share_button_tag("Hey you! Look at this secret!", :url => "#{ENV['DOMAIN_URL']}?secret=#{secret.id}") %>
						    	</div>
						  	</div>
						  	<div class="card-footer text-muted">
						  		<div class="upvotes-container pull-right">
						  			Upvotes: <span id="upvotes-<%= secret.id %>"> <%= secret.upvotes %> </span>
						  		<div class="up-down-votes pull-right" style="padding-left: 30px;">
						  			<i class="fa fa-thumbs-up change-upvotes upvote" aria-hidden="true" data-action="upvote" data-secret="<%= secret.id %>"></i> | <i class="fa fa-thumbs-down change-upvotes downvote" aria-hidden="true" data-action="downvote" data-secret="<%= secret.id %>"></i>
						  		</div>
						  		</div>
						  		<a class="show-comments pull-left pointer"> <i class="fa fa-comment" aria-hidden="true"></i> <%= secret.comments.length %> <% if secret.comments.length == 1%> Comment <% else %> Comments <% end %> </a>
							</div>
							<div class="card-footer card-comments hidden">
								<div class="container">
									<div class="row"> 
										<div class="col-12 pull-left">
											<h5> Comments </h5>
										</div>
									</div>
									<div class="row comments-row" style="max-height: 200px; overflow-y: scroll;">
										<% secret.comments.each do |comment| %>
											<div class="col-12" style="margin-bottom: 10px;">
												<img src="https://api.adorable.io/avatars/100/comment-<%= comment.id %>" style="height: 30px; width: auto; border-radius: 50%; margin-left: 15px;">	<span style="padding-left: 15px; border-left: 1px solid #ededed;"> <%= comment.body %> </span> <span class="pull-right" style="font-size: 14px; color: #cdcdcd;"> <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago </span>
											</div>
										<% end %>
									</div>
									<div class="row">
										<div class="col-12 form-group">
											<input type="text-area" name="comment-body" class="form-control" placeholder="Type in your comment">
										</div>
										<div class="col-md-12">
											<span class="btn btn-secondary shadow pull-right send-comment"> Send </span>
										</div>
									</div>
								</div>
							</div>
						</div>	
					</div>
				</div>
			<% end %>	
		</div>
	</div>
</div>

<div class="report-confirmation" style="display: none;">
	<div class="row text-center">
		<div class="col-12 text-center">
			<h3> Thanks for keeping this place clean.</h3>
		</div>
		<div class="col-12 text-center">
			<h5> What's the reason this post is being reported?</h5>
		</div>
	</div>
	<div class="row" style="padding-top: 30px;">
		<div class="col-md-4 text-center">
			<span class="btn btn-disabled reported-btn"> Hate Speech </span>
		</div>
		<div class="col-md-4 text-center">
			<span class="btn btn-disabled reported-btn"> Sexual Harassment </span>
		</div>
		<div class="col-md-4 text-center">
			<span class="btn btn-disabled reported-btn"> Other </span>
		</div>
	</div>
</div>

<script>
	$('.report-box').on("click", function(){
		$(this).parent().html($('.report-confirmation').html())
	});


	$(document).on('click', '.reported-btn', function(){
		var card_block = $(this).parents('.card-block')
	    var secret_id = card_block.attr('data-secret');
	    $.ajax({
			method: "POST",
		  	url: "/secret/report?secret="+secret_id,
		  	success: function(data){
		  		console.log(data);
		  		if (data.status == "ok"){
		  			var html = '<div class="row"><div class="col-12 text-center"><h3> I will review the post and delete it if it goes against the rules, thank you! </h3></div></div>'
		  			card_block.html(html)
		  		}
		  	}
	  	})
	});
</script>

app/views/visitors/index.html.erb
<h3>Welcome</h3>

app/views/wizards/step1.html.erb
<div class="container wizard-container">
  <div class="row">
    <div class="col-md-8 offset-md-2 text-center card">
      <div class="card-header text-center shadow">
        <h4> You are </h4>
      </div>
      <%= render partial: 'steps_wizard', locals: {step: 1} %>
      <%= form_for @secret_wizard, as: :secret_wizard, url: validate_step_wizard_path do |f| %>
        <%= hidden_field_tag :current_step, 'step1' %>
        <div class="row">
          <div class="col-md-6 text-center">
            <%= f.radio_button :user_gender, 'Man', class: "gender-radio gender-male", "data-toggle": "tooltip", "data-placement": "top", title: "Speed lower than 5Mbps" %>
          </div>
          <div class="col-md-6 text-center">
            <%= f.radio_button :user_gender, 'Woman', class: "gender-radio gender-female", "data-toggle": "tooltip", "data-placement": "top", title: "Speed lower than 10Mbps" %>
          </div>
        </div>
        <div class="row text-center">
            <div class="col-12">
              <%= f.submit 'Next', class: "btn btn-primary shadow", style: "margin-top: 30px;" %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wizards/step2.html.erb
<div class="container wizard-container">
  	<div class="row">
	    <div class="col-md-8 offset-md-2 text-center card">
	    	<div class="card-header text-center shadow">
		        <h4> Your age </h4>
		    </div>
	    	<%= render partial: 'steps_wizard', locals: {step: 2} %>
			<%= form_for @secret_wizard, as: :secret_wizard, url: validate_step_wizard_path do |f| %>
			 	<%= hidden_field_tag :current_step, 'step2' %>
		  		<div class="row">
		  			<div class="col-md-10 offset-md-1 text-center">
		      			<div class="range-slider">
						  <input name="secret_wizard[user_age]" class="secret_wizard_secret_body range-slider__range" type="range" value="0" min="15" max="99">
						  <span class="range-slider__value">15</span>
						</div>
		   			</div>
		   		</div>
		   		<div class="row text-center">
		   			<div class="col-12">
		   				<%= f.submit 'Next', class: "btn btn-primary shadow", style: "margin-top: 30px;" %>
		   			</div>
		   		</div>
			<% end %>
		</div>
	</div>
</div>

<script>
	var rangeSlider = function(){
  var slider = $('.range-slider'),
      range = $('.range-slider__range'),
      value = $('.range-slider__value');
    
  slider.each(function(){
    range.on('input', function(){
      $(this).next(value).html(this.value);
    });
  });
};

rangeSlider();
</script>

app/views/wizards/step3.html.erb
<div class="container wizard-container">
	<div class="row">
		<div class="col-md-8 offset-md-2 text-center card">
			<div class="card-header text-center shadow">
        		<h4> Your secret </h4>
      		</div>
			<%= render partial: 'steps_wizard', locals: {step: 3} %>
			<%= form_for @secret_wizard, as: :secret_wizard, url: validate_step_wizard_path do |f| %>
			  	<%= hidden_field_tag :current_step, 'step3' %>
			  	<div class="row">
		  			<div class="col-md-10 offset-md-1">
		  				<div class="form-group">
		  					<%= f.text_area :secret_body, class: "form-control", style:"width: 100%;" %>
		  				</div>
		   			</div>
		   		</div>
		   		<div class="row">
		   			<div class="col-md-10 offset-md-1" style="text-align: left;">
		   				<ol>
		   					<li> Don't post any phone number and/or name of any person. This is illegal. </li>
		   					<li> Don't be rude. Avoid using offensive terms and insults. </li>
		   					<li> Write grammatically correct sentences. </li>
		   					<li> Don't judge anyone on sexual preferences, religion, ethnicity. </li>
		   				</ol>
		   			</div>
		   		</div>
			  	<div class="row text-center">
		   			<div class="col-12">
		   				<%= f.submit 'Next', class: "btn btn-primary shadow", style: "margin-top: 30px;" %>
		   			</div>
		   		</div>		  
			<% end %>
		</div>
	</div>
</div>